
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 7odaco
 */
public class AgeCalc extends javax.swing.JFrame {

    /**
     * Creates new form AgeCalc
     */
    int currentyear=2025;
    int currentmonth=5;
    public AgeCalc() {
        initComponents();
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        age1 = new javax.swing.JLabel();
        calcage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        age1.setText("Please enter the year u were born!");

        calcage.setText("Click here to start!");
        calcage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(age1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(calcage)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(age1)
                .addGap(43, 43, 43)
                .addComponent(calcage)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcageActionPerformed
 JOptionPane.showMessageDialog(null, "Please first type the year u were born and then type the month and just wait!");
 double hijri;
 double hijrimonths;
 int ageinhijri;
 int monthsinhijri;
 
String num=JOptionPane.showInputDialog(null, "Please enter the year!");
 int age=Integer.parseInt(num);
        if (age<=1950||age>=2025) {
            JOptionPane.showMessageDialog(null, "please enter a correct year between 1950 and 2025");
        }else {JOptionPane.showMessageDialog(null, " ur age is"+(age=currentyear-age));}
  int choice=JOptionPane.showInternalConfirmDialog(null, "Do u want to see more about yourself");
        if (choice==0) { 
            String month=JOptionPane.showInputDialog("please enter the month u were born");
            int hi=Integer.parseInt(month);
               int zodiac=Integer.parseInt(month);
               if(zodiac <1 || zodiac>12){
               JOptionPane.showMessageDialog(null, "please enter the right month!");
               }
               switch(zodiac){
                   
                 
                   case 1:{
                      
                       hijri=age*1.0307;
                       ageinhijri=(int)hijri;
                         hijrimonths=((hijri-ageinhijri)*12);
                          monthsinhijri=(int)hijrimonths;
                          int year=currentyear=age;
                          int born=currentmonth-hi;
                          int totalmonths=year*12+born;
                          int totaldays=totalmonths*30;
                          int totalweeks=totaldays/7;
                          int remainingdays=totaldays%7;
                          int totalhours=totaldays*24;
                            JOptionPane.showMessageDialog(null," ur age in hijri is "+ageinhijri+" and "+monthsinhijri+"months"+"\n"+"وبرجك هو برج الجدي"+"\n"+"ur age in months is"+totalmonths+"\n"+"ur age in days is"+totaldays+"\n"+"ur age in weeks is"+totalweeks+ "and "+remainingdays+"days"+"\n"+"ur age in days is "+totaldays+"\n"+"ur age in hours is"+totalhours);      
                                  
                          break;
                      
                       
                   }
                   case 2:{
                   
                          hijri=age*1.0307;
                       ageinhijri=(int)hijri;
                         hijrimonths=((hijri-ageinhijri)*12);
                          monthsinhijri=(int)hijrimonths;
                          int year=currentyear=age;
                          int born=currentmonth-hi;
                          int totalmonths=year*12+born;
                          int totaldays=totalmonths*30;
                          int totalweeks=totaldays/7;
                          int remainingdays=totaldays%7;
                          int totalhours=totaldays*24;
                            JOptionPane.showMessageDialog(null," ur age in hijri is "+ageinhijri+" and "+monthsinhijri+"months"+"\n"+"وبرجك هو برج الدلو"+"\n"+"ur age in months is"+totalmonths+"\n"+"ur age in days is"+totaldays+"\n"+"ur age in weeks is"+totalweeks+ "and "+remainingdays+"days"+"\n"+"ur age in days is "+totaldays+"\n"+"ur age in hours is"+totalhours);      
                                  
                          break;
                   }
                   case 3:{
                          hijri=age*1.0307;
                       ageinhijri=(int)hijri;
                         hijrimonths=((hijri-ageinhijri)*12);
                          monthsinhijri=(int)hijrimonths;
                          int year=currentyear=age;
                          int born=currentmonth-hi;
                          int totalmonths=year*12+born;
                          int totaldays=totalmonths*30;
                          int totalweeks=totaldays/7;
                          int remainingdays=totaldays%7;
                          int totalhours=totaldays*24;
                            JOptionPane.showMessageDialog(null," ur age in hijri is "+ageinhijri+" and "+monthsinhijri+"months"+"\n"+"وبرجك هو برج الحوت"+"\n"+"ur age in months is"+totalmonths+"\n"+"ur age in days is"+totaldays+"\n"+"ur age in weeks is"+totalweeks+ "and "+remainingdays+"days"+"\n"+"ur age in days is "+totaldays+"\n"+"ur age in hours is"+totalhours);      
                                  
                          break;
                   
                   
                   }
                   case 4:{
                          hijri=age*1.0307;
                       ageinhijri=(int)hijri;
                         hijrimonths=((hijri-ageinhijri)*12);
                          monthsinhijri=(int)hijrimonths;
                          int year=currentyear=age;
                          int born=currentmonth-hi;
                          int totalmonths=year*12+born;
                          int totaldays=totalmonths*30;
                          int totalweeks=totaldays/7;
                          int remainingdays=totaldays%7;
                          int totalhours=totaldays*24;
                            JOptionPane.showMessageDialog(null," ur age in hijri is "+ageinhijri+" and "+monthsinhijri+"months"+"\n"+"وبرجك هو برج الحمل"+"\n"+"ur age in months is"+totalmonths+"\n"+"ur age in days is"+totaldays+"\n"+"ur age in weeks is"+totalweeks+ "and "+remainingdays+"days"+"\n"+"ur age in days is "+totaldays+"\n"+"ur age in hours is"+totalhours);      
                                  
                          break;
                   }
                   case 5:{
                          hijri=age*1.0307;
                       ageinhijri=(int)hijri;
                         hijrimonths=((hijri-ageinhijri)*12);
                          monthsinhijri=(int)hijrimonths;
                          int year=currentyear=age;
                          int born=currentmonth-hi;
                          int totalmonths=year*12+born;
                          int totaldays=totalmonths*30;
                          int totalweeks=totaldays/7;
                          int remainingdays=totaldays%7;
                          int totalhours=totaldays*24;
                            JOptionPane.showMessageDialog(null," ur age in hijri is "+ageinhijri+" and "+monthsinhijri+"months"+"\n"+"وبرجك هو برج الثور"+"\n"+"ur age in months is"+totalmonths+"\n"+"ur age in days is"+totaldays+"\n"+"ur age in weeks is"+totalweeks+ "and "+remainingdays+"days"+"\n"+"ur age in days is "+totaldays+"\n"+"ur age in hours is"+totalhours);      
                                  
                          break;
                   }
                   case 6:{
                          hijri=age*1.0307;
                       ageinhijri=(int)hijri;
                         hijrimonths=((hijri-ageinhijri)*12);
                          monthsinhijri=(int)hijrimonths;
                          int year=currentyear=age;
                          int born=currentmonth-hi;
                          int totalmonths=year*12+born;
                          int totaldays=totalmonths*30;
                          int totalweeks=totaldays/7;
                          int remainingdays=totaldays%7;
                          int totalhours=totaldays*24;
                            JOptionPane.showMessageDialog(null," ur age in hijri is "+ageinhijri+" and "+monthsinhijri+"months"+"\n"+"وبرجك هو برج الجوزاء"+"\n"+"ur age in months is"+totalmonths+"\n"+"ur age in days is"+totaldays+"\n"+"ur age in weeks is"+totalweeks+ "and "+remainingdays+"days"+"\n"+"ur age in days is "+totaldays+"\n"+"ur age in hours is"+totalhours);      
                                  
                          break;
                   
                   }
                   case 7:{
                          hijri=age*1.0307;
                       ageinhijri=(int)hijri;
                         hijrimonths=((hijri-ageinhijri)*12);
                          monthsinhijri=(int)hijrimonths;
                          int year=currentyear=age;
                          int born=currentmonth-hi;
                          int totalmonths=year*12+born;
                          int totaldays=totalmonths*30;
                          int totalweeks=totaldays/7;
                          int remainingdays=totaldays%7;
                          int totalhours=totaldays*24;
                            JOptionPane.showMessageDialog(null," ur age in hijri is "+ageinhijri+" and "+monthsinhijri+"months"+"\n"+"وبرجك هو برج السرطان"+"\n"+"ur age in months is"+totalmonths+"\n"+"ur age in days is"+totaldays+"\n"+"ur age in weeks is"+totalweeks+ "and "+remainingdays+"days"+"\n"+"ur age in days is "+totaldays+"\n"+"ur age in hours is"+totalhours);      
                                  
                          break;
                   
                   }
                   case 8:{
                          hijri=age*1.0307;
                       ageinhijri=(int)hijri;
                         hijrimonths=((hijri-ageinhijri)*12);
                          monthsinhijri=(int)hijrimonths;
                          int year=currentyear=age;
                          int born=currentmonth-hi;
                          int totalmonths=year*12+born;
                          int totaldays=totalmonths*30;
                          int totalweeks=totaldays/7;
                          int remainingdays=totaldays%7;
                          int totalhours=totaldays*24;
                            JOptionPane.showMessageDialog(null," ur age in hijri is "+ageinhijri+" and "+monthsinhijri+"months"+"\n"+"وبرجك هو برج الاسد"+"\n"+"ur age in months is"+totalmonths+"\n"+"ur age in days is"+totaldays+"\n"+"ur age in weeks is"+totalweeks+ "and "+remainingdays+"days"+"\n"+"ur age in days is "+totaldays+"\n"+"ur age in hours is"+totalhours);      
                                  
                          break;
                   }
                   case 9:{
                          hijri=age*1.0307;
                       ageinhijri=(int)hijri;
                         hijrimonths=((hijri-ageinhijri)*12);
                          monthsinhijri=(int)hijrimonths;
                          int year=currentyear=age;
                          int born=currentmonth-hi;
                          int totalmonths=year*12+born;
                          int totaldays=totalmonths*30;
                          int totalweeks=totaldays/7;
                          int remainingdays=totaldays%7;
                          int totalhours=totaldays*24;
                            JOptionPane.showMessageDialog(null," ur age in hijri is "+ageinhijri+" and "+monthsinhijri+"months"+"\n"+"وبرجك هو برج العذراء"+"\n"+"ur age in months is"+totalmonths+"\n"+"ur age in days is"+totaldays+"\n"+"ur age in weeks is"+totalweeks+ "and "+remainingdays+"days"+"\n"+"ur age in days is "+totaldays+"\n"+"ur age in hours is"+totalhours);      
                                  
                          break;
                   }
                   case 10:{
                          hijri=age*1.0307;
                       ageinhijri=(int)hijri;
                         hijrimonths=((hijri-ageinhijri)*12);
                          monthsinhijri=(int)hijrimonths;
                          int year=currentyear=age;
                          int born=currentmonth-hi;
                          int totalmonths=year*12+born;
                          int totaldays=totalmonths*30;
                          int totalweeks=totaldays/7;
                          int remainingdays=totaldays%7;
                          int totalhours=totaldays*24;
                            JOptionPane.showMessageDialog(null," ur age in hijri is "+ageinhijri+" and "+monthsinhijri+"months"+"\n"+"وبرجك هو برج الميزان"+"\n"+"ur age in months is"+totalmonths+"\n"+"ur age in days is"+totaldays+"\n"+"ur age in weeks is"+totalweeks+ "and "+remainingdays+"days"+"\n"+"ur age in days is "+totaldays+"\n"+"ur age in hours is"+totalhours);      
                                  
                          break;
                   
                   }
                   case 11:{
                          hijri=age*1.0307;
                       ageinhijri=(int)hijri;
                         hijrimonths=((hijri-ageinhijri)*12);
                          monthsinhijri=(int)hijrimonths;
                          int year=currentyear=age;
                          int born=currentmonth-hi;
                          int totalmonths=year*12+born;
                          int totaldays=totalmonths*30;
                          int totalweeks=totaldays/7;
                          int remainingdays=totaldays%7;
                          int totalhours=totaldays*24;
                            JOptionPane.showMessageDialog(null," ur age in hijri is "+ageinhijri+" and "+monthsinhijri+"months"+"\n"+"وبرجك هو برج العقرب"+"\n"+"ur age in months is"+totalmonths+"\n"+"ur age in days is"+totaldays+"\n"+"ur age in weeks is"+totalweeks+ "and "+remainingdays+"days"+"\n"+"ur age in days is "+totaldays+"\n"+"ur age in hours is"+totalhours);      
                                  
                          break;
                   
                   }
                   case 12:{
                          hijri=age*1.0307;
                       ageinhijri=(int)hijri;
                         hijrimonths=((hijri-ageinhijri)*12);
                          monthsinhijri=(int)hijrimonths;
                          int year=currentyear=age;
                          int born=currentmonth-hi;
                          int totalmonths=year*12+born;
                          int totaldays=totalmonths*30;
                          int totalweeks=totaldays/7;
                          int remainingdays=totaldays%7;
                          int totalhours=totaldays*24;
                            JOptionPane.showMessageDialog(null," ur age in hijri is "+ageinhijri+" and "+monthsinhijri+"months"+"\n"+"وبرجك هو برج القوس"+"\n"+"ur age in months is"+totalmonths+"\n"+"ur age in days is"+totaldays+"\n"+"ur age in weeks is"+totalweeks+ "and "+remainingdays+"days"+"\n"+"ur age in days is "+totaldays+"\n"+"ur age in hours is"+totalhours);      
                                  
                          break;
                   
                   }
                   default:JOptionPane.showMessageDialog(null, "please enter the right month!!!!");
               }
        
        }else JOptionPane.showMessageDialog(null, "As u wish sir!!");
        
     
       
       
       
    }//GEN-LAST:event_calcageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgeCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgeCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgeCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgeCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgeCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age1;
    private javax.swing.JButton calcage;
    // End of variables declaration//GEN-END:variables
}
