import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 7odaco
 */
public class Electronicwallet extends javax.swing.JFrame {

    /**
     * Creates new form Electronicwallet
     */
 double ILS=0.0;
 double USD=0.0;
 double JOD=0.0;



    public  Electronicwallet() {
        initComponents();
        scorelabel.setText("credit score"+ Appdata.creditscore);
              setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
              if(Appdata.creditscore>=50){
              ILS=ILS+2;
              Appdata.creditscore-=50;
              }
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        check = new javax.swing.JButton();
        dep = new javax.swing.JButton();
        with = new javax.swing.JButton();
        scorelabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        check.setText("Check balance");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        dep.setText("Deposit ");
        dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depActionPerformed(evt);
            }
        });

        with.setText("Withdraw");
        with.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withActionPerformed(evt);
            }
        });

        scorelabel.setText("Ur score will be shown here!");

        jButton1.setText("Rules");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(with, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(scorelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                        .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(325, 325, 325))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scorelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(with, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
      
   JOptionPane.showMessageDialog(null, " your balance in ILS is "+ILS +"\n"+" your balance in USD is "+USD+"\n"+" your balance in JOD is "+JOD);
    
    }//GEN-LAST:event_checkActionPerformed

    private void depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depActionPerformed

  JOptionPane.showMessageDialog(null, "Please for deposting money for each currency "+"\n"+"Type 1 for deposting ILS"+"\n"+"Type 2 for deposting USD"+"\n"+" type 3 for deposting JOD");
        String num1=JOptionPane.showInputDialog(null, "");
    int check=Integer.parseInt(num1);
  
  
     switch (check) {
         case 1:
             {
                 String num3=JOptionPane.showInputDialog(null, "Money deposit for ILS");
                 double num2=Double.parseDouble(num3);
                 if(num2>=10000 || num2<=1){
                   JOptionPane.showInternalMessageDialog(null, "Please read the rules again!");
                 }else  ILS=ILS+num2;
                
                 break;
             }
         case 2:
             {
                 String num3=JOptionPane.showInputDialog(null, "Money deposit for USD");
                 double num2=Double.parseDouble(num3);
                     if(num2>=5000 || num2<=1){
                   JOptionPane.showInternalMessageDialog(null, "Please read the rules again!");
                 }else   USD=USD+num2 ;
                
            
                 break;
             }
         case 3:
             {
                 String num3=JOptionPane.showInputDialog(null, "Money deposit for JOD");
                 double num2=Double.parseDouble(num3);
                     if(num2>=3000 || num2<=1){
                   JOptionPane.showInternalMessageDialog(null, "Please read the rules again!");
                 }else   JOD=JOD+num2;
              
                 
                 break;
             }
         default:
             JOptionPane.showInternalMessageDialog(null, "Please enter a valid number");
             break;
     }
       
  
       
        
    }//GEN-LAST:event_depActionPerformed

    private void withActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withActionPerformed
      JOptionPane.showMessageDialog(null, "Please for Withdrawing money for each currency "+"\n"+"Type 1 for Withdrawing ILS"+"\n"+"Type 2 for Withdrowin in  USD"+"\n"+" type 3 for Withdrowing JOD");
        String num1=JOptionPane.showInputDialog(null, "Choose ur currency!");
    int check=Integer.parseInt(num1);
     switch (check) {
         case 1:
             {
                 String num3=JOptionPane.showInputDialog(null, "Money withdrawing for ILS");
                 double num2=Double.parseDouble(num3);
                 if(num2>ILS || num2<0){
                   JOptionPane.showInternalMessageDialog(null, "Sir u cant withdraw money less than 0 or money that is more than ur currently balance!");
                 }else ILS=ILS-num2;
                  break;
                 
                
             }
         case 2:
             {
                 String num3=JOptionPane.showInputDialog(null, "Money withdrawing for USD");
                 double num2=Double.parseDouble(num3);
                     if(num2>USD || num2<0){
                   JOptionPane.showInternalMessageDialog(null, "Sir u cant withdraw money less than 0 or money that is more than ur currently balance!");
                 }else USD=USD-num2;
                 
                 break;
             }
         case 3:
             {
                 String num3=JOptionPane.showInputDialog(null, "Money withdrawing for JOD");
                 double num2=Double.parseDouble(num3);
                     if(num2>JOD || num2<0){
                   JOptionPane.showInternalMessageDialog(null, "Sir u cant withdraw money less than 0 or money that is more than ur currently balance!");
                 }else JOD=JOD-num2;
                
                 break;
             }
         default:
             JOptionPane.showInternalMessageDialog(null, "Please enter a valid number for the currency!");
             break;
     }
       
    
    }//GEN-LAST:event_withActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      JOptionPane.showMessageDialog(null, "Please sir u cant deposit more than 10k ils"+"\n"+"and more than 5k usd"+"\n"+"and more than 3k jod!");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Electronicwallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Electronicwallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Electronicwallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Electronicwallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Electronicwallet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton check;
    private javax.swing.JButton dep;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel scorelabel;
    private javax.swing.JButton with;
    // End of variables declaration//GEN-END:variables

}