
import javax.swing.JOptionPane;
import java.util.Random;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 7odaco
 */
public class roppsc extends javax.swing.JFrame {

   

      int minv=1;
       int maxv=3;
         int val;
    public roppsc() {
        initComponents();
          setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b1.setText("Start the game!");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome to the rock paper and scissors game");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(86, 86, 86)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
      int userwins=0;
      int compwins=0;
        while(true){
       
JOptionPane.showMessageDialog(null, "Please read the instructions before you start!");

String choice2 = JOptionPane.showInputDialog(null, "Type your choice:\n1 = Rock\n2 = Paper\n3 = Scissors");

int choice1 = Integer.parseInt(choice2); 


Random rand = new Random();
int computerChoice = rand.nextInt(3) + 1; 

String userMove = "", comp = "", result = "";


          switch (choice1) {
              case 1:
                  userMove = "Rock";
                  break;
              case 2:
                  userMove = "Paper";
                  break;
              case 3:
                  userMove = "Scissors";
                  break;
              default:
                  JOptionPane.showMessageDialog(null, "please enter a number from 1 to 3");
                  return;
          }

          switch (computerChoice) {
              case 1: 
                  comp = "Rock";
                  break;
              case 2:
                  comp = "Paper";
                  break;
              default:
                  comp = "Scissors";
                  break;
          }
  

if (choice1 == computerChoice) {
    result = "Tie!";
} else if (
    (choice1 == 1 && computerChoice == 3) ||  
    (choice1 == 2 && computerChoice == 1) || 
    (choice1 == 3 && computerChoice == 2)    
) {
    result = "User wins";
    userwins++;
} else {
    result = "bot wins!";
    compwins++;
}
JOptionPane.showMessageDialog(null,"You chose: " + userMove +"\nComputer chose: " + comp +"\n\n" + result);
JOptionPane.showMessageDialog(null, "the score is "+"\n"+"Player ="+userwins+"\n"+"bot ="+compwins);
       int again= JOptionPane.showConfirmDialog(null, "do u want to play agin?");
           
         if(again!=0){
         break;}
}


        
      
    }//GEN-LAST:event_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(roppsc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(roppsc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(roppsc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(roppsc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new roppsc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
